/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
    checkstyle
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo1.maven.org/maven2")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

checkstyle {
    toolVersion = "8.41.1"
    configFile = file("config/checkstyle/google_checks.xml")
    isIgnoreFailures = true
}

dependencies {
    implementation("com.hierynomus", "sshj", "0.19.0")
    implementation("org.slf4j", "slf4j-api", "1.7.12")
    testImplementation("ch.qos.logback", "logback-classic", "1.1.3")
    testImplementation("mysql", "mysql-connector-java", "5.1.34")
    testImplementation("com.h2database", "h2", "1.4.183")
    testImplementation("org.apache.derby", "derby", "10.11.1.1")
    testImplementation("org.apache.derby", "derbynet", "10.11.1.1")
    testImplementation("org.apache.derby", "derbyclient", "10.11.1.1")
    testImplementation("org.apache.sshd", "sshd-core", "0.14.0")
    testImplementation("org.bouncycastle", "bcpg-jdk15on", "1.52")
    testImplementation("org.bouncycastle", "bcpkix-jdk15on", "1.52")
    testImplementation("org.testng", "testng", "6.10")
}

group = "com.cekrlic"
version = "1.0.0-SNAPSHOT"
description = "JDBC SSH"
java.sourceCompatibility = JavaVersion.VERSION_1_7

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.test {
    useTestNG()
}
