/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
    checkstyle
    id("com.github.johnrengelman.shadow") version "6.1.0"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo1.maven.org/maven2")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

checkstyle {
    toolVersion = "8.41.1"
    configFile = file("config/checkstyle/google_checks.xml")
    isIgnoreFailures = true
}

dependencies {
    implementation("com.hierynomus", "sshj", "0.31.0")
    implementation("org.slf4j", "slf4j-api", "1.7.30")
    testImplementation("org.postgresql", "postgresql", "42.2.19")
    testImplementation("ch.qos.logback", "logback-classic", "1.2.3")
    testImplementation("mysql", "mysql-connector-java", "8.0.23")
    testImplementation("com.h2database", "h2", "1.4.200")
    testImplementation("org.apache.derby", "derby", "10.15.2.0")
    testImplementation("org.apache.derby", "derbynet", "10.15.2.0")
    testImplementation("org.apache.derby", "derbyclient", "10.15.2.0")
    testImplementation("org.apache.sshd", "sshd-core", "2.6.0")
    testImplementation("org.bouncycastle", "bcpg-jdk15on", "1.68")
    testImplementation("org.bouncycastle", "bcpkix-jdk15on", "1.68")
    testImplementation("org.testng", "testng", "7.4.0")
}

group = "io.github.emotionbug"
version = "1.0.11"
description = "JDBC over SSH"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.test {
    useTestNG()
}
